# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 17:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# main.migrations.0005_note_id

class Migration(migrations.Migration):

    replaces = [(b'main', '0001_initial'), (b'main', '0002_auto_20160313_1651'), (b'main', '0003_note_author'), (b'main', '0004_auto_20160321_1035'), (b'main', '0005_note_id'), (b'main', '0006_auto_20160321_1134')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=16)),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 13, 16, 51, 33, 68935, tzinfo=utc))),
                ('modified_on', models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 13, 16, 51, 43, 492995))),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
