# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-12 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
