# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-13 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 13, 16, 51, 33, 68935, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 13, 16, 51, 43, 492995)),
            preserve_default=False,
        ),
    ]
