# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 08:58
from __future__ import unicode_literals

from django.db import migrations

def forward(apps, schema):
    Note = apps.get_model('main', 'Note')
    for note in Note.objects.all():
        note.hash = note.hash[:8]
        note.save()

def backward(apps, schema):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160327_1055'),
    ]

    operations = [
        migrations.RunPython(forward, backward)
    ]
