# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_refactor_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='hash',
            field=models.CharField(max_length=8),
        ),
    ]
