# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160327_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='senza titolo', max_length=160),
        ),
    ]
