# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 10:30
from __future__ import unicode_literals

from django.db import migrations, models

def forward(apps, schema_editor):
    Note = apps.get_model('main', 'Note')
    for i, note in enumerate(Note.objects.all().order_by('created_on')):
        assert note.id == 0
        note.id = i+1
        note.save()

def backward(apps, schema_editor):
    Note = apps.get_model('main', 'Note')
    Note.objects.update(id=0)

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20160321_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='id',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(forward),
    ]
