# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_note_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='hash',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
